// Generated by CoffeeScript 2.5.1
(function() {
  // ChangeMaker takes in a price and an array of coins and returns
  // the most efficient array of pennies, nickles, dimes, and quarters 
  // in change.
  var changeMaker, dime, nickel, penny, quarter, recursion;

  quarter = 0;

  penny = 0;

  nickel = 0;

  dime = 0;

  recursion = function(totalDifference) {
    if (totalDifference - 25 >= 0) {
      quarter++;
      totalDifference = totalDifference - 25;
      return recursion(totalDifference);
    }
    if (totalDifference - 10 >= 0) {
      quarter++;
      totalDifference = totalDifference - 10;
      return recursion(totalDifference);
    }
    if (totalDifference - 5 >= 0) {
      quarter++;
      totalDifference = totalDifference - 5;
      return recursion(totalDifference);
    }
    if (totalDifference - 1 >= 0) {
      quarter++;
      totalDifference = totalDifference - 1;
      return recursion(totalDifference);
    } else {
      return console.log([quarter, dime, nickel, penny]);
    }
  };

  changeMaker = function(price, payment) {
    var newArr, newPrice, totalDifference, totalPay;
    newArr = payment.map(function(x) {
      return x * 100;
    });
    newPrice = price * 100;
    console.log(newArr);
    totalPay = newArr.reduce(function(x, y) {
      return x + y;
    });
    totalDifference = totalPay - newPrice;
    console.log(totalDifference, " is my totalDifference");
    return recursion(totalDifference);
  };

  changeMaker(0.5, [0.25, 0.25, 0.25]);

}).call(this);
