// Generated by CoffeeScript 2.5.1
(function() {
  var coffee, coffeemaker;

  coffee = "volcanica";

  console.log(coffee + "is the best French Roast available!");

  coffeemaker = function() {
    return console.log("I am making a cup of" + coffee);
  };

}).call(this);
